vich_uploader:
    db_driver: orm
    
    mappings:
        file_id_card_img:
            uri_prefix: '%app.path.id.card.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.id.card.images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
