vich_uploader:
    db_driver: orm
    
    mappings:
        file_id_card_img:
            uri_prefix: '%app.path.id.card.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.id.card.images%'
